version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  pre_build:
    commands:
      - echo "Running unit tests..."
      - mvn test

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn package -DskipTests=true

artifacts:
  files:
    - target/*.jar  # Include the built JAR file